### ISSUE TITLE
No Web Framework

### ISSUE THREAD

**Issue by PC-LoadLetter** [dack/n1mm-display#2]
Darrell,
This is a very cool concept. My club is asking me to work on something exactly like what you've done here. I have N1MM running and I see new contacts in the console, but I don't see any reference to a localhost and port number for the web app. I checked netstat and there are no services running that at 127.0.0.1:80 or :8080....

If an external web framework is required do you have a recommendation?
Thanks,
Collins

**Comment by darrellenns** [comment]
The port it listens on is configured in settings.js. Take a look at settings.js.example to see all the options. It should also print out the listen port on the console when you start it up.

**Comment by PC-LoadLetter** [comment]
Thanks! It looks great. We will probably be using this at Loudoun Amateur Radio Group (K4LRG) during next year's field day. I'm going to share with some other clubs too. 73
